app/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from app import views
from app.views import *
from campaign.views import *

urlpatterns = [
    # Matches any html file 
    re_path(r'^.*\.html', views.pages, name='pages'),

    # The home page
    path('', views.index, name='home'),
    path('campaign/',campaign, name='campaign'),
    path('donation/', views.donation, name='donation'),
    path('update_profile/<str:pk>/', views.updateProfile, name="update_profile"),
    path('salaTime/<str:pk>/', views.salaTime, name="salaTime"),
    

]

core/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("authentication.urls")),  # add this
    path("", include("app.urls")),
    path('', include('users.urls')),
    path('', include('masjid.urls')),
    path('', include('campaign.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import date


class CustomUser(AbstractUser):
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    username = models.CharField(max_length=100, unique=False, null=True, blank=True)
    email = models.EmailField(unique=True, null=False)
    name = models.CharField(max_length=100, null=True)
    phone = models.CharField(max_length=35, null=False)
    gender = models.CharField(max_length=50, null=True)
    dob = models.DateField(null=True, auto_now = False)
    address  = models.CharField(max_length=500, null=True)
    status  = models.BooleanField(default=False)
    masjid_name = models.CharField(max_length=255, null=True)
    masjid_id = models.IntegerField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    card_info = models.BooleanField(default=False)
    cardName = models.CharField(max_length=55, null=True)
    donation_reference = models.CharField(max_length=50, null=True)
    updated_at = models.DateTimeField(null = True)
    stripe_customer_id = models.CharField(max_length=255, null=True)
    card_token = models.CharField(max_length=100, null=True)
    masjidCardName = models.CharField(max_length=100, null=True)
    verify_user  = models.BooleanField(default=False)
    masjidCardNumber = models.CharField(max_length=100, null=True)
    masjidAddress  = models.CharField(max_length=500, null=True)
    lat = models.CharField(max_length=100, null=True)
    lng = models.CharField(max_length=100, null=True)
    profile_pic = models.ImageField(upload_to='profile_pic', null=True)

    @property
    def full_name(self):
        name = ''
        if self.first_name:
            name += self.first_name
        if self.last_name:
            name += " " + self.last_name

        return name



class Feedback(models.Model):
    user_id = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='user_id')
    comment = models.CharField(max_length=250, null=True)
    feedback = models.FloatField(null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.userid.email

class Donation(models.Model):
    userId = models.IntegerField(null=True)
    object_id = models.CharField(max_length=255, null=True)
    masjid_id = models.IntegerField(null=True)
    amount = models.CharField(max_length=255, null=True)
    donation_reference = models.CharField(max_length=50, null=True)
    donation_for = models.CharField(max_length=50, null=True)
    payment_type = models.CharField(max_length=50, null=False)
    recurring_period = models.CharField(max_length=50, null=True)
    detail = models.CharField(max_length=255, null=True)
    starting_at = models.DateField(auto_now=False, null=True)
    next_at = models.DateField(auto_now=False, null=True)
    payment_status = models.BooleanField(default=True)
    charge_id = models.CharField(max_length=255, null=True)
    customer_id = models.CharField(max_length=255, null=True)
    cardToken = models.CharField(max_length=500, null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(null = True)

core/templates/accounts/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock %} 

{% block content %}

<style>
@media only screen and (min-width:1300px){
  body{
      overflow: hidden!important;
  }
}
</style>
<div class="container" id="login-page">
  <div class="row" id="login-page_id">
    <div class="col-md-6">
      <div class="col col-login1">
        <div class="text-center">
          <img class="login-side-logo" src="/static/assets/img/logo1.png" alt="">
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="row">
        <div class="col col-login mx-auto">
          <!-- <div class="text-center">
            <img src="/static/assets/demo/brand/tabler.svg" class="h-6" alt="">
          </div> -->
          <div class="card login-card log-page-mar">
            <h1 class="login-title mt-5">Login</h1>
                <div class="card-body pb-0">
                    <form class="" action="" method="post">
    
                    {% csrf_token %}
                    <div class="card-title text-center" style="color: #dc3545;">
        
                    {% if msg %}
                        {{ msg | safe }}
                    {% endif %}  
                    
                    </div>
        
                    <div class="form-group">
                    <!-- <label class="form-label">Username</label> -->
                    {{ form.email }}
                    </div>      
                    <div class="form-group">
                    <!-- <label class="form-label">
                        Password
                    </label> -->
                    {{ form.password }}
                    </div>
                    <div class="form-group">
                        <div class="row">
                        <div class="col-12">
                            <span class="remember-login ml-2">
                                <div class="round">
                                <input type="checkbox" id="checkbox"  name="remember_me"/>
                                <label for="checkbox"></label>
                                <span class="rem pl-1">Keep me sign in</span>
                                </div>
                                <label for=""> </label>
                            </span>
                            <a class="frgt forgot-login" href="auth-reset-pass.html"><span class="pl-2 rem">Forgot Password?</span></a>
                        </div>
                        </div>
                        <div class="row">
                            <div class="col-12 mt-5">
                                <div class="form-footer">
                                    <button type="submit" name="login" class="submit-login btn btn-primary btn-block mb-0">Login</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <div class="card-body pt-0">
                <div class="form-group">
                    <div class="row">
                        <div class="col-12">
                            <div class="form-footer">
                                <a class="signuplink" href={% url 'register' %} ><button  class="login-signup-btn btn btn-primary btn-block">Signup</button></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script>
  $(function() {
    if (localStorage.chkbx && localStorage.chkbx != '') {
        $('#checkbox').attr('checked', 'checked');
        $('#id_email').val(localStorage.email);
        $('#id_password').val(localStorage.pass);
    } else {
        $('#checkbox').removeAttr('checked');
        $('#id_email').val('');
        $('#id_password').val('');
    }
  });
  $('input:checkbox[name=remember_me]').click(function() {
    if ($('#checkbox').is(':checked')) {
      // save username and password
      localStorage.email = $('#id_email').val();
      localStorage.pass = $('#id_password').val();
      localStorage.chkbx = $('#checkbox').val();
    } else {
      localStorage.email = '';
      localStorage.pass = '';
      localStorage.chkbx = '';
    }
  });
</script>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<!-- <script>
  document.getElementById("checkbox").addEventListener("click")
</script> -->
{% endblock javascripts %}

core/templates/accounts/register2.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Signup {% endblock %} 

{% block content %}


<div class="container" id="login-page">
  <div class="row" id="signup-id">
    <div class="col-md-6" >
      <div class="col col-login1 mx-auto">
        <div class="text-center mt-3">
          <img class="login-side-logo" src="/static/assets/img/logo1.png" alt="">
        </div>
      </div>
    </div>
    <div class="col-md-6 mt-2">
      <div class="row">
        <div class="col col-login mx-auto ">
          <!-- <div class="text-center">
            <img src="/static/assets/demo/brand/tabler.svg" class="h-6" alt="">
          </div> -->
          <form class="signup-form" action="" method="post" id="signup-form">   
            {% csrf_token %}
            <div class="signup-step2 mt-3" id="signup-step2">
              <div class="card login-card">
                <h1 class="login-title mt-5">Account Details</h1>
                <div class="card-body pb-4">
                  <div class="card-title text-center" style="color: #dc3545;">
        
                    {% if msg %}
                      {{ msg | safe }}
                    {% endif %}  
                    
                  </div>
                  <div class="form-group">
                    <input type="text" name="account_name" id="account_name" class="form-control" placeholder="Trusted Account Name" required>
                  </div>
                  <div class="form-group">
                    <input type="number" name="account_no" id="account_no" oninput="this.value = this.value.replace(/[^0-9]/g, '').replace(/(\..*?)\..*/g, '$1');" class="form-control" placeholder="Trusted Account Number" required>
                  </div>  
                  <div class="form-group mt-3">
                    <div class="row">
                        <div class="col-12">
                            <div class="form-footer">
                                <button type="submit" class="submit-login btn btn-primary btn-block">Submit</button>
                                <a href="/" id="homeurl" style="text-decoration: none;"><button  class=" submit-login mt-2 btn btn-primary btn-block">Skip</button></a>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                      <!-- <div class="col-6 pt-2 text-left">
                          <span class="back mt-3"><img class="" src="/static/assets/img/left-arrow.png" alt="">Back</span>
                      </div> -->
                      <!-- <div class="col-6 pt-2 text-right">
                        <a class="decoration-none" href="/login/"><span class="login-arrow-c mt-3">Login<img class="" src="/static/assets/img/right-arrow-c.png" alt=""></span></a>
                      </div> -->
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </form>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script>
    $("#homeurl").on("click",function(){ 
      var origin   = window.location.origin;
      window.location.replace(origin);
    });
    // $(".back").on("click",function(){
    //     $("#signup-step1").show()
    //     $("#signup-step2").hide();
    // });
    // var error_msg = {{msg | safe}};
</script>

{% endblock javascripts %}

core/templates/accounts/register3.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Signup {% endblock %} 

{% block content %}


<div class="container" id="login-page">
  <div class="row" id="signup-id">
    <div class="col-md-6" >
      <div class="col col-login1 mx-auto">
        <div class="text-center mt-3">
          <img class="login-side-logo" src="/static/assets/img/logo1.png" alt="">
        </div>
      </div>
    </div>
    <div class="col-md-6 mt-2">
      <div class="row">
        <div class="col col-login mx-auto ">
          <!-- <div class="text-center">
            <img src="/static/assets/demo/brand/tabler.svg" class="h-6" alt="">
          </div> -->
          <form class="signup-form" action="" method="post" id="signup-form">   
            {% csrf_token %}
            <div id="signup-step1" >
              <div class="card login-card pt-4">
                <h1 class="login-title">Sign up</h1>
                <div class="card-body pt-1">
                  <div class="card-title text-center" style="color: #dc3545;">
        
                    {% if msg %}
                      {{ msg | safe }}
                    {% endif %}  
                    
                  </div>
                  <div class="form-group">
                      <input type="text" name="masjid_name" id="masjid_name" class="form-control" placeholder="Masjid or Center Name" required>
                  </div>
                  <div class="form-group">
                      <input type="text" name="address" id="address" class="form-control" placeholder="Address" required>
                  </div>  
                  <div class="form-group">
                      <input type="tel" class="form-control getphone" name="phone_number" id="phone_number" value="" style="width: 100%;" required/>
                      <span class="tel-error" style="color: #dc3545;display: none;">Enter numbers without country code.</span>
                  </div>
                  <div class="form-group">
                      <input type="email" name="email" id="email" class="form-control" placeholder="Email" required>
                  </div>
                  <div class="form-group">
                      <input type="password" name="password1" id="password1" class="form-control" placeholder="Password" required>
                  </div>
                  <div class="form-group">
                      <input type="password" name="password2" id="password2" class="form-control" placeholder="Confirm Password" required>
                  </div>
                  <div class="form-group">
                      <div id="locationField">
                          <input id="autocomplete" class="form-control" name="address2" placeholder="Enter your address" onFocus="geolocate()" type="text" required/>
                      </div>
                  </div>
                  <div class="form-group pb-0">
                      <div class="row">
                          <div class="col-12">
                              <div class="form-footer">
                                  <div class="submit-login btn btn-primary btn-block" id="btn-next">Next<img class="ml-1" src="/static/assets/img/right-arrow.png" alt=""></div>
                              </div>
                          </div>
                      </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="signup-step2" id="signup-step2" style="display: none;">
              <div class="card login-card">
                <h1 class="login-title mt-5">Account Details</h1>
                <div class="card-body pb-4">
                  <div class="form-group">
                    <input type="text" name="account_name" id="account_name" class="form-control" placeholder="Trusted Account Name">
                  </div>
                  <div class="form-group">
                    <input type="number" name="account_no" id="account_no" oninput="this.value = this.value.replace(/[^0-9]/g, '').replace(/(\..*?)\..*/g, '$1');" maxlength="16" minlength="16" class="form-control" placeholder="Trusted Account Number">
                  </div>  
                  <div class="form-group mt-3">
                    <div class="row">
                        <div class="col-12">
                            <div class="form-footer">
                                <button type="submit" class="submit-login btn btn-primary btn-block">Sign up</button>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                      <div class="col-6 pt-2 text-left">
                          <span class="back mt-3"><img class="" src="/static/assets/img/left-arrow.png" alt="">Back</span>
                      </div>
                      <!-- <div class="col-6 pt-2 text-right">
                        <a class="decoration-none" href="/login/"><span class="login-arrow-c mt-3">Login<img class="" src="/static/assets/img/right-arrow-c.png" alt=""></span></a>
                      </div> -->
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </form>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBbcRKoAUxva1_KIYbyQ0O2U4SpMIUlu2E&callback=initAutocomplete&libraries=places&v=weekly" async></script>
<script>
    $.ajax({
        url: "http://ip-api.com/json",
        jsonpCallback: "callback",
        dataType: "jsonp",
        success: function( response ) {
            var phone_number = window.intlTelInput(document.querySelector("#phone_number"), {
                separateDialCode: true,
                preferredCountries: [response.countryCode],
                hiddenInput: "full",
                utilsScript: "//cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.3/js/utils.js"

            });
            $('#phone_number').on('change paste keyup', function(){
                var inputnum = $(this).val();
                var onlynumbers = /^[0-9]+$/;
                if(inputnum.match(onlynumbers)){
                    $(".tel-error").css("display","none");
                }else{
                    $(".tel-error").css("display","block")
                    return false;
                }
                
            });
            $("#signup-form").submit(function(){
                var full_number = phone_number.getNumber(intlTelInputUtils.numberFormat.E164);
                $("input[name='phone_number'").val(full_number);
            });
        }
    });
</script>
<script>
    let placeSearch;
    let autocomplete;
    const componentForm = {
        street_number: "short_name",
        route: "long_name",
        locality: "long_name",
        administrative_area_level_1: "short_name",
        country: "long_name",
        postal_code: "short_name",
    };

function initAutocomplete() {
  // Create the autocomplete object, restricting the search predictions to
  // geographical location types.
  autocomplete = new google.maps.places.Autocomplete(
    document.getElementById("autocomplete"),
    { types: ["geocode"] }
  );
  // Avoid paying for data that you don't need by restricting the set of
  // place fields that are returned to just the address components.
  autocomplete.setFields(["address_component"]);
  // When the user selects an address from the drop-down, populate the
  // address fields in the form.
  autocomplete.addListener("place_changed", fillInAddress);
}

function fillInAddress() {
  // Get the place details from the autocomplete object.
  const place = autocomplete.getPlace();

  for (const component in componentForm) {
    document.getElementById(component).value = "";
    document.getElementById(component).disabled = false;
  }

  // Get each component of the address from the place details,
  // and then fill-in the corresponding field on the form.
  for (const component of place.address_components) {
    const addressType = component.types[0];

    if (componentForm[addressType]) {
      const val = component[componentForm[addressType]];
      document.getElementById(addressType).value = val;
    }
  }
}

// Bias the autocomplete object to the user's geographical location,
// as supplied by the browser's 'navigator.geolocation' object.
function geolocate() {
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition((position) => {
      const geolocation = {
        lat: position.coords.latitude,
        lng: position.coords.longitude,
      };
      const circle = new google.maps.Circle({
        center: geolocation,
        radius: position.coords.accuracy,
      });
      autocomplete.setBounds(circle.getBounds());
    });
  }
}
</script>
<script>
    $("#btn-next").on("click",function(){
        $("#signup-step1").hide()
        $("#signup-step2").show();
    });
    $(".back").on("click",function(){
        $("#signup-step1").show()
        $("#signup-step2").hide();
    });
    // var error_msg = {{msg | safe}};
</script>
{% endblock javascripts %}

core/templates/accounts/reset-pass.html
{% extends "layouts/base1.html" %}

{% block title %} Login {% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="/static/assets/css/accounts.css">


{% endblock stylesheets %}

{% block content %}

    <div class="page-inner">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4 centered text-center">
                <div class="card card1">
                    <!-- <div class="row">
                        <div class="col-md-12 col-lg-12">
                            <img src="/static/assets/img/loginlogo.png" alt="..." class="" style="height:100px;width:97px;">
                        </div>
                    </div> -->
                    <div class="m-auto img-box"><img class="login-logo" src="/static/assets/img/loginlogo.png" alt="semafore-logo"> <br><span>SemaFore</span></div>
                    {% if msg %}
                        <p style="color: #0d9a0d;font-size: 15px; margin-bottom: 0px;">
                            {{ msg | safe }}
                        </p>
                    {% endif %}
                    {% if msg1 %}
                        <p style="color: #a50c0c;font-size: 15px; margin-bottom: 0px;">
                            {{ msg1 | safe }}
                        </p>
                    {% endif %}
                    <form action="" method="POST" id="login-form">

                        {% csrf_token %}

                        <div class="card-body">
                            <div class="row" id="reset">
                                <div class="col-md-12 col-lg-12">
                                    <div class="form-group">
                                        <div class="input-group">
                                            {{ form.email }}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="input-group">
                                            <input class="submit-login" type="submit" value="Submit">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </form>

                </div>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}
    <script>
        $( document ).ready(function() {
            if ($("#login-from").valid()){
                console.log("it is valid");
            }
        });
    </script>
{% endblock javascripts %}

core/templates/accounts/reset-password.html
{% extends "layouts/base1.html" %}

{% block title %} Login {% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="/static/assets/css/accounts.css">
    <style>
        label{
            /* display: none; */
            color: #ffffff00!important;
            margin-bottom: 0px!important;
        }
    </style>

{% endblock stylesheets %}

{% block content %}

    <div class="page-inner">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4 centered text-center">
                <div class="card card1">
                    <!-- <div class="row">
                        <div class="col-md-12 col-lg-12">
                            <img src="/static/assets/img/loginlogo.png" alt="..." class="" style="height:100px;width:97px;">
                        </div>
                    </div> -->
                    <div class="m-auto img-box"><img class="login-logo" src="/static/assets/img/loginlogo.png" alt="semafore-logo"> <br><span>SemaFore</span></div>
                    {% if msg %}
                        <p style="color: #dc3545;font-size: 15px; margin-bottom: 0px;">
                            {{ msg | safe }}
                        </p>
                    {% endif %}
                    <form method="post" action="" id="login-form">

                        {% csrf_token %}

                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12 col-lg-12 text-left">
                                    
                                    <div class="form-group">
                                        {{form}}
                                    </div>

                                    <!-- <div class="form-group">
                                        <div class="input-group">
                                            {{ form.password1 }}
                                        </div>
                                    </div> -->
                                    <div class="form-group">
                                        <div class="input-group">
                                            <input class="submit-login" type="submit" value="Submit">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </form>

                </div>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}
    <script>
        $( document ).ready(function() {
            if ($("#login-from").valid()){
                console.log("it is valid");
            }
        });
    </script>
{% endblock javascripts %}